"""Merge shared and per-wheel Fibre config with protected operating limits.

custom_odrive commission exec's a single .py with odrv / enums / math injected.
Kanga keeps common settings in shared_motor_config.py and identity / overrides
in wheel_<id>_motor_config.py. This module concatenates shared then individual,
so an ordinary individual assignment wins when both files set the same field.
Validated velocity and acceleration limits are appended last and therefore
cannot be bypassed by either editable motor file.

Used by:
  commission_wheels.py  — CLI / drive_manager calibrate path
  test_config_merge.py  — offline unit checks (no CAN / Fibre)

Example layout under config/motors/:
  shared_motor_config.py      # watchdog, gains, … shared by all wheels
  wheel_fl_motor_config.py    # node_id, any FL-only overrides
  wheel_bl_motor_config.py
  …
"""

from __future__ import annotations

from pathlib import Path


# Canonical drive wheel ids — keep aligned with drive.launch.py / drive_manager.
WHEEL_IDS = ("fl", "bl", "br", "fr")


# Resolve the per-wheel Fibre configuration path.
def motor_config_path(motors_dir: Path, wheel_id: str) -> Path:
    """Return path to wheel_<id>_motor_config.py under motors_dir."""
    wheel_id = wheel_id.strip().lower()
    if wheel_id not in WHEEL_IDS:
        raise ValueError(f"Unknown wheel id {wheel_id!r}; expected one of {WHEEL_IDS}")
    return motors_dir / f"wheel_{wheel_id}_motor_config.py"


# Combine shared settings, a wheel-specific overlay, and protected limits.
def merge_motor_configs(
    shared_path: Path,
    wheel_path: Path,
    motor_velocity_limit_tps: float,
    motor_acceleration_limit_tps_s: float,
) -> str:
    """Return shared, individual, then final protected-limit assignments.

    Order matters: Fibre scripts are plain Python executed top-to-bottom, so
    fields set in the wheel file overwrite the same attribute from shared. The
    protected footer then restores the validated operating limits.
    """
    shared = shared_path.read_text(encoding="utf-8")
    wheel = wheel_path.read_text(encoding="utf-8")
    if motor_velocity_limit_tps <= 0.0:
        raise ValueError("motor_velocity_limit_tps must be > 0")
    if motor_acceleration_limit_tps_s <= 0.0:
        raise ValueError("motor_acceleration_limit_tps_s must be > 0")
    header = (
        "# Auto-generated by kanga_core_drive: shared_motor_config.py + "
        f"{wheel_path.name}\n"
    )
    protected_limits = (
        "\n\n# Protected operating limits appended by kanga_core_drive.\n"
        "# These validated assignments intentionally run after editable files.\n"
        f"MOTOR_VELOCITY_LIMIT_TPS = {motor_velocity_limit_tps!r}\n"
        f"MOTOR_ACCELERATION_LIMIT_TPS_S = {motor_acceleration_limit_tps_s!r}\n"
        "odrv.axis0.controller.config.vel_limit = MOTOR_VELOCITY_LIMIT_TPS\n"
        "odrv.axis0.controller.config.vel_ramp_rate = "
        "MOTOR_ACCELERATION_LIMIT_TPS_S\n"
    )
    return header + shared.rstrip() + "\n\n" + wheel.strip() + protected_limits


# Write a temporary merged Fibre configuration for commissioning.
def write_merged_config(
    shared_path: Path,
    wheel_path: Path,
    dest: Path,
    motor_velocity_limit_tps: float,
    motor_acceleration_limit_tps_s: float,
) -> Path:
    """Write merge_motor_configs(...) to dest and return dest.

    dest is typically a tempfile under /tmp used once by commission, then deleted.
    """
    dest.write_text(
        merge_motor_configs(
            shared_path,
            wheel_path,
            motor_velocity_limit_tps,
            motor_acceleration_limit_tps_s,
        ),
        encoding="utf-8",
    )
    return dest
