"""Merge shared + per-wheel Fibre motor config files for commissioning.

custom_odrive commission exec's a single .py with odrv / enums / math injected.
Kanga keeps common settings in shared_motor_config.py and identity / overrides
in wheel_<id>_motor_config.py; this module concatenates shared then overlay
(so later assignments win if both set the same field).

Used by:
  commission_wheels.py  — CLI / drive_manager calibrate path
  test_config_merge.py  — offline unit checks (no CAN / Fibre)

Example layout under config/motors/:
  shared_motor_config.py      # watchdog, gains, … shared by all wheels
  wheel_fl_motor_config.py    # node_id, any FL-only overrides
  wheel_bl_motor_config.py
  …
"""

from __future__ import annotations

from pathlib import Path


# Canonical drive wheel ids — keep aligned with drive.launch.py / drive_manager.
WHEEL_IDS = ("fl", "bl", "br", "fr")


def motor_config_path(motors_dir: Path, wheel_id: str) -> Path:
    """Return path to wheel_<id>_motor_config.py under motors_dir."""
    wheel_id = wheel_id.strip().lower()
    if wheel_id not in WHEEL_IDS:
        raise ValueError(f"Unknown wheel id {wheel_id!r}; expected one of {WHEEL_IDS}")
    return motors_dir / f"wheel_{wheel_id}_motor_config.py"


def merge_motor_configs(shared_path: Path, wheel_path: Path) -> str:
    """Return concatenated config source: shared first, then wheel overlay.

    Order matters: Fibre scripts are plain Python executed top-to-bottom, so
    fields set in the wheel file overwrite the same attribute from shared.
    """
    shared = shared_path.read_text(encoding="utf-8")
    wheel = wheel_path.read_text(encoding="utf-8")
    # Header is documentation only; commission ignores comments.
    header = (
        "# Auto-generated by kanga_core_drive: shared_motor_config.py + "
        f"{wheel_path.name}\n"
    )
    return header + shared.rstrip() + "\n\n" + wheel.lstrip()


def write_merged_config(shared_path: Path, wheel_path: Path, dest: Path) -> Path:
    """Write merge_motor_configs(...) to dest and return dest.

    dest is typically a tempfile under /tmp used once by commission, then deleted.
    """
    dest.write_text(merge_motor_configs(shared_path, wheel_path), encoding="utf-8")
    return dest
