#!/usr/bin/env python3
"""Convert a grayscale heightmap into one deterministic shared terrain mesh."""

from argparse import ArgumentParser
from pathlib import Path
import math

from PIL import Image


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--size-x", type=float, required=True)
    parser.add_argument("--size-y", type=float, required=True)
    parser.add_argument("--size-z", type=float, required=True)
    parser.add_argument("--sample-step", type=int, default=1)
    args = parser.parse_args()

    if args.sample_step < 1:
        parser.error("--sample-step must be at least one")

    source = Image.open(args.source).convert("L")
    columns = list(range(0, source.width, args.sample_step))
    rows = list(range(0, source.height, args.sample_step))
    if columns[-1] != source.width - 1:
        columns.append(source.width - 1)
    if rows[-1] != source.height - 1:
        rows.append(source.height - 1)

    width = len(columns)
    height = len(rows)
    dx = args.size_x / (width - 1)
    dy = args.size_y / (height - 1)
    elevations = [
        [source.getpixel((column, row)) / 255.0 * args.size_z for column in columns]
        for row in rows
    ]

    def normal(row: int, column: int) -> tuple[float, float, float]:
        left = max(0, column - 1)
        right = min(width - 1, column + 1)
        above = max(0, row - 1)
        below = min(height - 1, row + 1)
        dz_dx = (elevations[row][right] - elevations[row][left]) / (
            (right - left) * dx
        )
        # Image rows run from +Y to -Y in the generated mesh.
        dz_dy = (elevations[above][column] - elevations[below][column]) / (
            (below - above) * dy
        )
        nx, ny, nz = -dz_dx, -dz_dy, 1.0
        length = math.sqrt(nx * nx + ny * ny + nz * nz)
        return nx / length, ny / length, nz / length

    with args.destination.open("w", encoding="ascii", newline="\n") as output:
        output.write("# Generated by heightmap_to_obj.py; do not edit manually.\n")
        output.write(
            f"# source={args.source.name} samples={width}x{height} "
            f"size={args.size_x:g}x{args.size_y:g}x{args.size_z:g}m\n"
        )
        output.write("mtllib sand_dunes_terrain.mtl\n")
        output.write("o sand_dunes_terrain\n")
        output.write("usemtl loose_sand\n")
        for row in range(height):
            y = args.size_y * 0.5 - row * dy
            for column in range(width):
                x = -args.size_x * 0.5 + column * dx
                output.write(f"v {x:.8f} {y:.8f} {elevations[row][column]:.8f}\n")
        for row in range(height):
            for column in range(width):
                nx, ny, nz = normal(row, column)
                output.write(f"vn {nx:.8f} {ny:.8f} {nz:.8f}\n")
        for row in range(height - 1):
            for column in range(width - 1):
                top_left = row * width + column + 1
                top_right = top_left + 1
                bottom_left = top_left + width
                bottom_right = bottom_left + 1
                output.write(
                    f"f {top_left}//{top_left} {bottom_left}//{bottom_left} "
                    f"{top_right}//{top_right}\n"
                )
                output.write(
                    f"f {top_right}//{top_right} {bottom_left}//{bottom_left} "
                    f"{bottom_right}//{bottom_right}\n"
                )


if __name__ == "__main__":
    main()
